# Generated by Django 5.2.4 on 2025-08-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('veiculo', models.CharField(choices=[('Moto', 'Moto'), ('Bicicleta', 'Bicicleta'), ('Carro', 'Carro')], max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('localizacao_atual', models.CharField(blank=True, help_text="Coordenadas GPS (ex: '-23.5505, -46.6333')", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_entrega', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Preparando'), ('R', 'Em rota'), ('E', 'Entregue')], default='P', max_length=1)),
                ('prioridade', models.CharField(choices=[('N', 'Normal'), ('U', 'Urgente')], default='N', max_length=1)),
                ('data_hora_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produtos', models.JSONField(blank=True, default=list, help_text="Lista de produtos no formato JSON. Ex: [{'nome': 'Remédio X', 'quantidade': 2}]")),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.cliente')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.entregador')),
            ],
            options={
                'ordering': ['-data_hora_pedido'],
            },
        ),
    ]
