# Generated by Django 5.2.4 on 2025-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_lojista_alter_pedido_options_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_hora_pedido']},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='acompanhepedido',
            name='localizacao_atual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
